### ISSUE TITLE
ขี้โกง

### ISSUE THREAD

**Issue by gongpha** [gongpha/PPCProject#1]
![image](https://github.com/gongpha/PPCProject/assets/13400398/2d1a26c8-a292-4e38-ae0d-6b3eae7008cd)
@nkarGn มาคุยดิ

**Comment by nkarGn** [comment]
ก็มาดิ

**Comment by gongpha** [comment]
ยาอ่อน

**Comment by nkarGn** [comment]
https://media.discordapp.net/attachments/1001094981710262343/1167208174512779374/FB_IMG_1698244609093.jpg?ex=654d4a52&is=653ad552&hm=6412443aaece2f1367817219991c0f20d5368d63db5c23248ee1017a881cda64&=&width=1016&height=1356

**Comment by gongpha** [comment]
Leave a comment

**Comment by nkarGn** [comment]
ก็เพราะตอนนี้มันมีแค่เรา 🔥🔥🔥🔥🦐🦐🦐🦐🦐🦐🦐🍺🍺🍺🍺🦐🦐🔥🔥🔥🔥ตอนนี้ต้องการแค่เมา🔥🔥🦐🍺🍺🦐🦐🔥ถ้าไม่มีเขาคงไม่เท่าไร🔥🔥🔥🔥🦐🦐🦐🦐🦐🦐🦐🍺🍺🍺🍺🦐🦐🔥🔥🔥🔥ไม่ต้องไปร้องไม่ต้องเสียใจ🔥🔥🦐🦐🦐🍺🍺🥴มึงชูแก้วแล้วมึงก็ชน🗣️🔥🗣️🔥🗣️🔥ถ้ามันจะไปก็ไปต้องมาทุกข์ต้องมาทน🥂🥂🕺🕺🥵🥵🦞🦞🦞🦐🦐🦐🍻🍻🦐🦐🦞🦞💃💃🏃‍♂️🏃‍♂️

**Comment by gongpha** [comment]
ไม่เพราะเลย ร้องไม่รู้เรื่อง เหมือนบ่นอะไรสักอย่าง ดัดเสียง จูนเสียง พยายามทำให้เสียงหล่อจนดูไม่เป็นธรรมชาติ เสียงเหมือนคนที่มีค่า BMI เกินมาตรฐานเหมือนคนปากแหว่งเพดานโหว่ ลิ้นไก่สั้น เสียงเหมือนคนเป็นโรคไซนัสหรือไม่ก็มีปัญหาทางโพรงจมูก หรืออาจจะมีลักษณะดั้งที่แหมบ เสียงไม่ถึงจริง ๆ บางท่อนเสียงขึ้นจมูกน่าเกลียดมาก ร้องไม่เต็มเสียง เลยดูฝืน ๆ สรุปโดยรวม คือ ฟังรอบเดียวแล้วทำให้รู้สึกว่าไม่อยากจะฟังต่อ

![lmao](https://cdn.discordapp.com/attachments/1038996352278995044/1168222938403704862/395303671_347060497986273_815917311687256155_n.jpg?ex=6550fb65&is=653e8665&hm=9658d173342f7c92a9af96e665f130bf16b68be25eaa0928de2ffc93474c1018&)

**Comment by gongpha** [comment]
![FB_IMG_1698436266547.jpg](https://github.com/gongpha/PPCProject/assets/13400398/4ebae2f1-2738-48af-8ef4-16477bdfd848)

มำไมไมตอบ
